name: Deploy to Server

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add server to known_hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to Server
      run: |
        ssh deploy@${{ secrets.SERVER_IP }} "
          cd /home/nicola/app-money/app &&
          git fetch --tags &&
          git checkout '${{ github.ref_name }}' &&
          git reset --hard &&
          git clean -fd &&
          cd /home/nicola/app-money &&
          source venv/bin/activate &&
          pip install --upgrade pip &&
          pip install -r app/requirements.txt &&
          sudo systemctl restart moneyflow.service
        "
