name: Deploy to Server

on:
  push:
    tags:
      - 'v*'  # Trigger solo su push di tag tipo "v1.0.0"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_DIR: /home/nicola/app-money/app
      PROJECT_ROOT: /home/nicola/app-money
      SERVICE_NAME: moneyflow.service

    steps:
    - name: Checkout code (for context only)
      uses: actions/checkout@v3

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add Server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh deploy@${{ secrets.SERVER_IP }} "
          set -e

          echo 'Switching to project directory: $APP_DIR'
          cd $APP_DIR

          echo 'Fetching tags...'
          git fetch --tags

          echo 'Checking out tag: ${{ github.ref_name }}'
          git checkout '${{ github.ref_name }}'

          echo 'Cleaning working directory...'
          git reset --hard
          git clean -fd

          echo 'Moving to root: $PROJECT_ROOT'
          cd $PROJECT_ROOT

          echo 'Activating virtual environment...'
          source venv/bin/activate

          echo 'Upgrading pip...'
          pip install --upgrade pip

          echo 'Installing dependencies...'
          pip install -r app/requirements.txt

          echo 'Restarting service: $SERVICE_NAME'
          sudo systemctl restart $SERVICE_NAME

          echo 'Deploy completed successfully.'
        "
