name: Deploy to Server

on:
  push:
    tags:
      - 'v*'  # Trigger solo su tag v1.0.0 ecc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ROOT: /home/${{ secrets.DEPLOY_USER }}/app-money
      APP_DIR: /home/${{ secrets.DEPLOY_USER }}/app-money/app
      SERVICE_NAME: moneyflow.service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add Server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Ensure remote directories exist
      run: |
        ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} "mkdir -p ${{ env.APP_DIR }} && chmod 755 /home/${{ secrets.DEPLOY_USER }}/app-money"

    - name: Sync code to server
      run: |
        rsync -az --delete --no-times --exclude '.git' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }}:${{ env.APP_DIR }}

    - name: Remote setup and restart
      run: |
        ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} "
          set -e
          cd $PROJECT_ROOT
          if [ ! -d venv ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r app/requirements.txt
          sudo systemctl restart $SERVICE_NAME
        "
